//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VisitTime
    {
        public int ID { get; set; }
        public Nullable<int> IdPation { get; set; }
        public Nullable<int> IdJoinDocAndSecAndServ { get; set; }
        public Nullable<System.DateTime> EnterviewDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    
        public virtual Tbl_JoinDoctorAndSectionAndService Tbl_JoinDoctorAndSectionAndService { get; set; }
        public virtual Tbl_Patient Tbl_Patient { get; set; }
    }
}
