//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Service()
        {
            this.Tbl_JoinDoctorAndSectionAndService = new HashSet<Tbl_JoinDoctorAndSectionAndService>();
        }
    
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public string Major { get; set; }
        public Nullable<int> Price { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_JoinDoctorAndSectionAndService> Tbl_JoinDoctorAndSectionAndService { get; set; }
    }
}
