//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Logins
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
    
        public virtual Tbl_Roles Tbl_Roles { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
