//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_JoinDoctorAndSectionAndService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_JoinDoctorAndSectionAndService()
        {
            this.Tbl_VisitTime = new HashSet<Tbl_VisitTime>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDoctors { get; set; }
        public Nullable<int> IdSection { get; set; }
        public Nullable<int> IdService { get; set; }
    
        public virtual Tbl_Doctors Tbl_Doctors { get; set; }
        public virtual Tbl_Section Tbl_Section { get; set; }
        public virtual Tbl_Service Tbl_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_VisitTime> Tbl_VisitTime { get; set; }
    }
}
