//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Doctors()
        {
            this.Tbl_JoinDoctorAndSectionAndService = new HashSet<Tbl_JoinDoctorAndSectionAndService>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string NatinalCode { get; set; }
        public string Major { get; set; }
        public string Degree { get; set; }
        public string BirthDate { get; set; }
        public string Tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_JoinDoctorAndSectionAndService> Tbl_JoinDoctorAndSectionAndService { get; set; }
    }
}
