//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_App_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viw_VisitTime
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string DocterFaamily { get; set; }
        public string SecName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> EnterviewDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    }
}
